#!/usr/bin/env python

import string
import random
import gzip
import os.path
from Crypto.Random import random

WORDS='/usr/share/dict/words',



def ok_word( word):
	letter = not any((c not in string.ascii_lowercase) for c in word)
	size = 3 < len( word)
	nono = word in ['fuck', 'fucker', 'cock']
	return letter and size and not nono

def clean( word):
	return word[:word.find('/')]


f = open('/usr/share/dict/words', 'r')
all_words = f.readlines()

clean_dict = [clean( word) for word in all_words]
dictionary = [word for word in clean_dict if ok_word( word)]

#print 'Dictionary length: ', len(dictionary)

pwd_words = [random.choice( dictionary) for _ in range(0,4)]
print '.'.join( pwd_words)


